string time_stamp
string dvl_status
float64 temperature
float64 temperature_min
float64 temperature_max
string temperature_unit
float64 sound_speed
float64 sound_speed_min
float64 sound_speed_max
string sound_speed_unit
float64 pressure
float64 pressure_min
float64 pressure_max
string pressure_unit
#Bottom-Track, Beam based Velocity data
float64 bottom_vel_min
float64 bottom_vel_max
string bottom_vel_unit
float64 bottom_vel_1_data
float64 bottom_vel_2_data
float64 bottom_vel_3_data
float64 bottom_vel_4_data
float64 bottom_vel_1_status
float64 bottom_vel_2_status
float64 bottom_vel_3_status
float64 bottom_vel_4_status
#Bottom-Track, Beam based FOM data
float64 bottom_fom_min
float64 bottom_fom_max
string bottom_fom_unit
float64 bottom_fom_1_data
float64 bottom_fom_2_data
float64 bottom_fom_3_data
float64 bottom_fom_4_data
float64 bottom_fom_1_status
float64 bottom_fom_2_status
float64 bottom_fom_3_status
float64 bottom_fom_4_status
#Bottom-Track, Beam based Distance data
float64 bottom_dist_min
float64 bottom_dist_max
string bottom_dist_unit
float64 bottom_dist_1_data
float64 bottom_dist_2_data
float64 bottom_dist_3_data
float64 bottom_dist_4_data
float64 bottom_dist_1_status
float64 bottom_dist_2_status
float64 bottom_dist_3_status
float64 bottom_dist_4_status
#Bottom-Track, XYZ Velocity data
float64 bottom_xyz_vel_min
float64 bottom_xyz_vel_max
string bottom_xyz_vel_unit
float64 bottom_xyz_vel_1_data
float64 bottom_xyz_vel_2_data
float64 bottom_xyz_vel_3_data
float64 bottom_xyz_vel_4_data
float64 bottom_xyz_vel_1_status
float64 bottom_xyz_vel_2_status
float64 bottom_xyz_vel_3_status
float64 bottom_xyz_vel_4_status
#WATER-MASS, INSTRUMENT-REFERENCED VELOCITY DATA
float64 wi_x_axis 
float64 wi_y_axis 
float64 wi_z_axis 
float64 wi_error 
string wi_status 
#BOTTOM-TRACK, INSTRUMENT-REFERENCED VELOCITY DATA
float64 bi_x_axis 
float64 bi_y_axis 
float64 bi_z_axis 
float64 bi_error 
string bi_status 
#WATER-MASS, SHIP-REFERENCED VELOCITY DATA
float64 ws_transverse 
float64 ws_longitudinal 
float64 ws_normal 
string ws_status 
#BOTTOM-TRACK, SHIP-REFERENCED VELOCITY DATA
float64 bs_transverse 
float64 bs_longitudinal 
float64 bs_normal 
string bs_status 
#WATER-MASS, EARTH-REFERENCED VELOCITY DATA
float64 we_east 
float64 we_north 
float64 we_upwards 
string  we_status 
#BOTTOM-TRACK, EARTH-REFERENCED VELOCITY DATA
float64 be_east 
float64 be_north 
float64 be_upwards 
string  be_status 
#  WATER-MASS, EARTH-REFERENCED DISTANCE DATA
float64 wd_east 
float64 wd_north 
float64 wd_upwards 
float64 wd_range 
float64 wd_time 
#BOTTOM-TRACK, EARTH-REFERENCED DISTANCE DATA
float64 bd_east 
float64 bd_north 
float64 bd_upwards 
float64 bd_range 
float64 bd_time
#RAW DATA 
string raw_data
